name: Birthday Reminder Cron

on:
  schedule:
    - cron: "*/10 * * * *"   # every 5 minutes for testing purposes
  workflow_dispatch:

jobs:
  birthday:
    runs-on: ubuntu-latest

    steps:
      - name: Call birthday cron endpoint
        run: |
          curl -X GET https://birthdayreminder-8wsw.onrender.com/cron/birthday \
            -H "x-cron-secret: ${{ secrets.CRON_SECRET }}"
